utils/updatechroot: source config automatically

diff --git a/utils/update-chroot b/utils/update-chroot
--- a/utils/update-chroot
+++ b/utils/update-chroot
@@ -1,6 +1,13 @@
 #!/bin/sh
 MYDIR=$(dirname "$(readlink -f "$0")")
+export H="$MYDIR/.."
+source "$H"/config
 
-cp -r $MYDIR/../pkg $R/src/
-cp -r $MYDIR/../KEEP $R/src/
+if [ -z "$R" ] ; then
+	echo "error sourcing config" >&2
+	exit 1
+fi
+
+cp -r "$H"/pkg "$R"/src/
+cp -r "$H"/KEEP "$R"/src/
 
