fix apache "portable" runtime for x-compile
apr uses a braindead propietary pkg-config clone, which of course was
designed without a clue about crosscompiling or non-default install locations.
so trying to x-compile anything using apr is a PITA and requires a shitload
of hacks to fix.

they even ship their own libtool clone, which is of course buggy as well:
while it works for compiling, the link invocation calls a hardcoded "gcc"
rather than the linker name that was passed on the command line (would equal
to $CC).

as such, i had to use libtool.cross.gen to overwrite their libtool version,
however their usage case seems to hit a bashism in libtool.cross,
so we have to add bash as a dependency until libtool.cross gets fixed.

diff --git a/pkg/apr b/pkg/apr
--- a/pkg/apr
+++ b/pkg/apr
@@ -12,10 +12,27 @@ sha512=1842e2dfc9315d9dd39acd4545d80fad45dcb419c9bfb4423453ca8727aa78d864fd48f43
 http://archive.apache.org/dist/apr/apr-1.4.6.tar.bz2
 
 [build]
-CFLAGS="-include stdlib.h -include pwd.h -D_GNU_SOURCE -DSTDC_HEADERS" ./configure -C \
+[ -n "$CROSS_COMPILE" ] && \
+  xconfflags="--host=$($CC -dumpmachine|sed 's/musl/gnu/')"
+sizeof_iovec=0
+for sz in 8 12 16 ; do
+	printf "#include <sys/socket.h>\ntypedef int foo[(sizeof(struct iovec)==$sz) * 2 -1];\n" > tmp.$$.c
+	if $CC -c tmp.$$.c ; then
+		sizeof_iovec=$sz
+		break
+	fi
+done
+[ $sizeof_iovec = 0 ] && { echo "ERROR: could not determine sizeof(struct iovec)" ; exit 1 ; }
+CFLAGS="$optcflags" \
+LDFLAGS="$optldflags" \
+CPPFLAGS="-include stdlib.h -include pwd.h -D_GNU_SOURCE -DSTDC_HEADERS" \
+  ./configure -C $xconfflags \
   --prefix="$butch_prefix" --datadir="$butch_prefix"/share/apr \
   apr_cv_accept4=yes ac_cv_func_inet_addr=yes ac_cv_func_inet_network=yes \
   ac_cv_tcp_nodelay_inherited=yes ac_cv_o_nonblock_inherited=no \
+  ac_cv_file__dev_zero=yes apr_cv_process_shared_works=yes \
+  apr_cv_mutex_robust_shared=no apr_cv_tcp_nodelay_with_cork=yes \
+  ac_cv_sizeof_struct_iovec=$sizeof_iovec \
 || exit 1
 make -j$MAKE_THREADS || exit 1
 make DESTDIR="$butch_install_dir" install || exit 1
