gcc473: fix for cross-compilation

diff --git a/pkg/gcc473 b/pkg/gcc473
--- a/pkg/gcc473
+++ b/pkg/gcc473
@@ -29,6 +29,11 @@ fi
 patch -p1 < "$K"/gcc473-unwind-dliterate.patch || exit 1
 patch -p1 < "$K"/gcc473-dliterate-configure-var.patch || exit 1
 patch -p1 < "$K"/gcc473-arm-hwcap.patch || exit 1
+patch -p1 < "$K"/gcc473-config-sub.patch || exit 1
+
+# fix specs file generation. this prevents libgcc_s from being used.
+# not only is it slower, it'll cause assertion errors in ld.
+sed -i 's,-lgcc_s,-lgcc_eh -lc,' gcc/gcc.c
 
 # we're doing a bit of hack to place the g++ contents in this folder
 # the build system isnt really laid out for extracting multiple tarballs into
@@ -80,10 +85,17 @@ elif [ "$A" = "powerpc" ] ; then
 	config_arch_target_ldflags="-Wl,--secure-plt"
 fi
 
+machine=
+if [ -n "$CROSS_COMPILE" ] ; then
+	machine=$($CC -dumpmachine)
+	xconfflags="--host=$machine --target=$machine"
+	export GCC_FOR_TARGET="$CC"
+fi
 export CC="$CC -static -D_GNU_SOURCE"
 
 CFLAGS="-O0 -s" LDFLAGS="-Wl,--no-keep-memory" \
-CFLAGS_FOR_TARGET="$config_arch_target_cflags" LDFLAGS_FOR_TARGET="$config_arch_target_ldflags" \
+CFLAGS_FOR_TARGET="$config_arch_target_cflags" \
+LDFLAGS_FOR_TARGET="$config_arch_target_ldflags" \
 ./configure -C --with-headers=no --prefix="$butch_prefix" \
   --disable-multilib --disable-nls --disable-mudflap \
   --disable-libmudflap --enable-libssp --disable-libgomp \
@@ -92,7 +104,7 @@ CFLAGS_FOR_TARGET="$config_arch_target_cflags" LDFLAGS_FOR_TARGET="$config_arch_
   --with-system-zlib \
   --with-target-libiberty=no --with-target-zlib=no \
   --enable-languages=c,c++ --enable-clocale=generic \
-  $config_arch_flags || exit 1
+  $config_arch_flags $xconfflags || exit 1
 
 
 gcc_cv_libc_provides_ssp=yes \
@@ -103,20 +115,12 @@ make -j1 DESTDIR="$butch_install_dir" \
 dest=$butch_install_dir$butch_prefix
 
 #create a host_tuple dummy entry, so binutils stuff will get into /bin, etc
-lib_gcc=`$dest/bin/gcc -print-libgcc-file-name`
-lib_gcc_minus_filename=`echo $lib_gcc | sed "$VERSION_REMOVE"`
-host_tuple=`basename $lib_gcc_minus_filename`
-echo host tuple is $host_tuple
+[ -z $machine ] && machine=$($dest/bin/gcc -dumpmachine)
 
-if [ ! -e ${dest}/${host_tuple} ] ; then
-	(
-	cd $dest
-	ln -sf . ${host_tuple}
-	)
-fi
+[ ! -e ${dest}/${machine} ] && 	( cd $dest ; ln -sf . ${machine} )
 
 #remove gcc's stddef.h which is not compatible
-rm $dest/lib/gcc/$host_tuple/$VERSION/include/stddef.h
+rm $dest/lib/gcc/$machine/$VERSION/include/stddef.h
 
 copy() {
 	printf "cp %s %s\n" "$1" "$2"
@@ -126,21 +130,11 @@ copy() {
 echo link gcc intrinsic headers into /include/gcc
 # this allows usage of -I/include/gcc for stuff that uses them
 mkdir -p  $dest/include/gcc
-for i in $dest/lib/gcc/$host_tuple/$VERSION/include/* ; do
+for i in $dest/lib/gcc/$machine/$VERSION/include/* ; do
   header=`basename "$i"`
   # do not copy headers that exist in musl
   [ -e "$dest/include/$header" ] || copy "$i" "$dest/include/gcc/"
 done
-
-# fix specs file. this prevents libgcc_s from being used.
-# not only is it slower, it'll cause assertion errors in ld.
-# the default location for this file is relative from the gcc
-# binary used, "gccdir"/lib/gcc/$host_tuple/$gcc-version/specs
-# the second default path is "gccdir"/lib/gcc/specs. we use
-# the latter to use less movable parts.
-
-"$dest"/bin/gcc -dumpspecs > "$dest"/lib/gcc/specs || exit 1
-sed -i 's,-lgcc_s,-lgcc_eh -lc,' "$dest"/lib/gcc/specs
 
 if [ "$A" = x86_64 ] ; then
 	mv "$dest"/lib64/* "$dest"/lib/ || true
