changes needed to build gcc4 without --disable-shared
basically, we want the "shared" support.
this fixes some issues, especially the invalid code generation one
on mips due to libgcc.a built with no visibility "hidden".
an additional advantage is that libstdc++ builds both dynamic and
shared libraries, so we dont need libstdc++-dynamic anymore.
this saves about 1 minute of build time.
otoh we have to build stage0_musl now with dynamic library support.
otherwise the building of the shared libstdc++ will fail.
due to this change, the build time improvements are mostly even.

however this opens a new can of worms:
by default, the specfile links to libgcc_s for dynamic linking.
this is somehow broken, ld reports assert failures whenever
libgcc_s is on the command line. also its slower than using
a static linked copy.
with --disable-shared libgcc.a contains libgcc_eh.a.
this is now no longer the case, so things depending on C++ like
exception handling in C (like luajit) fail to build.
so we create a default spec file, and instead of just stripping
-lgcc_s out of it, we replace it with -lgcc_eh.

another fix is needed for the libstdc++.la (libtool) files, they
reference /lib/../lib64. this reference is then taken from packages
using it, and hardcoded into their own la files. any libtool-using
program linking to one of those libs (tiff, pango, glib) will then
try to find libstdc++.la in that directory.

diff --git a/pkg/gcc4 b/pkg/gcc4
--- a/pkg/gcc4
+++ b/pkg/gcc4
@@ -108,7 +108,28 @@ for i in $dest/lib/gcc/$host_tuple/4.5.4/include/* ; do
   [ -e "$dest/include/$header" ] || copy "$i" "$dest/include/gcc/"
 done
 
+# install musl specs file. this prevents libgcc_s from being used.
+# not only is it slower, it'll cause assertion errors in ld.
+# the default location for this file is relative from the gcc
+# binary used, "gccdir"/lib/gcc/$host_tuple/$gcc-version/specs
+# the second default path is "gccdir"/lib/gcc/specs. we use
+# the latter to use less movable parts.
+if false ; then
+  # gcc doesnt like the first line of the specs file,
+  # but without that line gcc -E spits out weird statistics.
+  # thus we have to resort to using gcc's spec with lgcc_s removed.
+  cp "$K"/musl-gcc.specs "$dest"/lib/gcc/specs || exit 1
+  sed -i "s,AAAA,$A," "$dest"/lib/gcc/specs
+else
+  "$dest"/bin/gcc -dumpspecs > "$dest"/lib/gcc/specs || exit 1
+#  sed -i 's, --as-needed -lgcc_s --no-as-needed, -lgcc_eh,' "$dest"/lib/gcc/specs
+  sed -i 's,-lgcc_s,-lgcc_eh,' "$dest"/lib/gcc/specs
+fi
 
-[ "$A" = x86_64 ] && mv $dest/lib64/* $dest/lib/ || true
+if [ "$A" = x86_64 ] ; then
+	mv "$dest"/lib64/* "$dest"/lib/ || true
+	sed -i 's,/lib/../lib64,/lib,' "$dest"/lib/libstdc++.la
+	sed -i 's,/lib/../lib64,/lib,' "$dest"/lib/libsupc++.la
+fi
 
 ln -sf gcc "$dest"/bin/cc
