gcc4: add some assertions so we dont get a broken libstdc++
see issue #76

diff --git a/pkg/gcc4 b/pkg/gcc4
--- a/pkg/gcc4
+++ b/pkg/gcc4
@@ -16,6 +16,15 @@ tardir=gcc-4.5.4
 http://ftpmirror.gnu.org/gcc/gcc-4.5.4/gcc-core-4.5.4.tar.bz2
 
 [build]
+# check that libc.so is available, otherwise we'll get a libstdc++.so
+# that is statically linked against musls libc.a.
+# this will lead to random crashes in C++ apps since two concurrent
+# malloc implementations will call brk and mess up each other.
+if [ ! -f "$butch_prefix"/lib/libc.so ] ; then
+	echo "libc.so non-existing or symlink broken"
+	exit 1
+fi
+
 #busybox awk doesnt like the two calls to attribute_mode function which is commented out
 sed -i '/   *attribute_mode/s@attr@#&@' gcc/config/i386/i386-builtin-types.awk
 
@@ -138,3 +147,10 @@ if [ "$A" = x86_64 ] ; then
 fi
 
 ln -sf gcc "$dest"/bin/cc
+
+# assert that libstdc++.so is not statically linked against musl
+if ! readelf -a "$dest"/lib/libstdc++.so | grep NEEDED | grep libc.so > /dev/null ; then
+	echo "error: libstdc++.so has no NEEDED entry for libc.so!"
+	exit 1
+fi
+
