bump kernel, grsec, gradm to linux 3.8

diff --git a/pkg/kernel b/pkg/kernel
--- a/pkg/kernel
+++ b/pkg/kernel
@@ -1,15 +1,15 @@
 [deps]
 gcc4
 xz
+grsec
 
 [mirrors]
-http://www.kernel.org/pub/linux/kernel/v3.x/linux-3.3.4.tar.xz
-http://kambing.ui.ac.id/linux/v3.0/linux-3.3.4.tar.xz
+http://www.kernel.org/pub/linux/kernel/v3.0/linux-3.8.tar.xz
+http://kambing.ui.ac.id/linux/v3.0/linux-3.8.tar.xz
 
 [main]
-
-filesize=65856460
-sha512=a42f238f06278365969393db841d0d4ddc61a4d2093dda759c177366dc1f43e30a2c71309f07214fc881367ee0c185c819af929b5817185e83943894a8c1718e
+filesize=70989468
+sha512=10a7983391af907d8aec72bdb096d1cabd4911985715e9ea13d35ff09095c035db15d4ab08b92eda7c10026cc27348cb9728c212335f7fcdcda7c610856ec30f
 
 [build]
 # get into menuconfig using
@@ -17,32 +17,33 @@ sha512=a42f238f06278365969393db841d0d4ddc61a4d2093dda759c177366dc1f43e30a2c71309
 
 dopatch() {
 	echo "applying patch $1"
-	patch -p1 < "$1" || (echo "patch failed!"; exit 1)
+	if ! patch -p1 < "$1" ; then
+		echo "patch failed!"
+		exit 1
+	fi
 }
 
-#this patch seems to come from chneukirchen original sabotage
-dopatch $K/linux-posix-sed.patch
-
 #noperl and qemu patches from landley.net/aboriginal
-dopatch $K/linux-noperl-capflags.patch 
-dopatch $K/linux-noperl-headers.patch
-dopatch $K/linux-noperl-timeconst.patch
-dopatch $K/linux-arm.patch 
-dopatch $K/linux-bootraw.patch
-dopatch $K/linux-fixsh4.patch 
-dopatch $K/linux-mips64fix.patch
-dopatch $K/linux-pmacorder.patch
-dopatch $K/linux-fixubi.patch
+dopatch "$K"/linux-noperl-capflags.patch 
+dopatch "$K"/linux-noperl-headers.patch
+dopatch "$K"/linux-noperl-timeconst.patch
+
 # fix the broken "ncurses detector" which fails, and even worse removes our HOSTLDFLAGS
-dopatch $K/linux-menuconfig.patch
+dopatch "$K"/linux-menuconfig.patch
+
+# patches to support busybox trap and sed with strict musl BRE engine
+dopatch "$K"/linux-3.8-trap.patch
+dopatch "$K"/linux-3.8-posix_sed.patch
 
 if [ -z "$DISABLE_GRSEC" ] ; then
-	#grsecurity and pax
-	#dopatch $K/pax-linux-3.3.4-test9.patch
-	dopatch $K/grsecurity-2.9-3.3.4-201204272006.patch
+	tar xf "$C"/grsecurity-2.9.1-3.8.0-201302231124.patch.tar.xz
+	dopatch grsecurity-2.9.1-3.8.0-201302231124.patch
+	# the patch is buggy and adds some includes that are non-existing at all points.
+	dopatch "$K"/grsecurity-2.91patch.patch
 fi
+
 export ARCH=$A
-linux_config="$K/linux.config"
+linux_config="$K"/linux.config
 
 if [ -z "$HOSTCC" ] ; then
 	HOSTCC="$CC"
@@ -53,11 +54,14 @@ if [ "$A" = arm ] ; then
 	linux_config="$linux_config $K/linux.config.armv${ARM_ARCH}l"
 fi
 
-cat $linux_config > my.config
+cat "$linux_config" > my.config
 
-make allnoconfig HOSTCFLAGS="-D_GNU_SOURCE" KCONFIG_ALLCONFIG=my.config DISABLE_PAX_PLUGINS=y || exit 1
+make V=1 ARCH=$A allnoconfig HOSTCFLAGS="-D_GNU_SOURCE" \
+  KCONFIG_ALLCONFIG=my.config DISABLE_PAX_PLUGINS=y || exit 1
 
-make ARCH=$A HOSTCFLAGS=-D_GNU_SOURCE INSTALL_HDR_PATH=dest DISABLE_PAX_PLUGINS=y headers_install || exit 1
+make V=1 ARCH=$A HOSTCFLAGS=-D_GNU_SOURCE INSTALL_HDR_PATH=dest \
+  DISABLE_PAX_PLUGINS=y headers_install || exit 1
+
 find dest/include \( -name .install -o -name ..install.cmd \) -delete
 
 # FIXME clean up $R usage
@@ -74,9 +78,12 @@ fi
 if [ -z "$SKIP_KERNEL_COMPILE" ] ; then
 
 #let make create dependencies, otherwise parallel build wont work
-make CC="$CC" HOSTCC="$HOSTCC" ARCH=$A HOSTCFLAGS=-D_GNU_SOURCE DISABLE_PAX_PLUGINS=y dep || exit 1
+make v=1 CC="$CC" HOSTCC="$HOSTCC" ARCH=$A HOSTCFLAGS=-D_GNU_SOURCE \
+  DISABLE_PAX_PLUGINS=y dep || exit 1
 
-make -j$MAKE_THREADS CC="$CC" V=1 ARCH=$A HOSTCC="$HOSTCC" HOSTCFLAGS=-D_GNU_SOURCE DISABLE_PAX_PLUGINS=y || exit 1
+make V=1 -j$MAKE_THREADS CC="$CC" ARCH=$A HOSTCC="$HOSTCC" \
+  HOSTCFLAGS=-D_GNU_SOURCE DISABLE_PAX_PLUGINS=y || exit 1
+
 make INSTALL_MOD_PATH=$R DISABLE_PAX_PLUGINS=y modules_install || exit 1
 
 mkdir -p $R/boot $R/lib/modules $R/lib/firmware
