protobuf: version bump, fix x-compile
closes #250

diff --git a/pkg/protobuf b/pkg/protobuf
--- a/pkg/protobuf
+++ b/pkg/protobuf
@@ -1,14 +1,21 @@
 [mirrors]
-http://protobuf.googlecode.com/files/protobuf-2.5.0.tar.bz2
+https://github.com/google/protobuf/releases/download/2.6.1/protobuf-2.6.1.tar.bz2
 
 [main]
-filesize=1866763
-sha512=5994b3669808b82fef5c860ecad36358c0767f84acac877e7bfcf722e59d972835a955714149bdd4158fbd1328a51d01397a563991d26475351ee72be48142ee
+filesize=2021416
+sha512=8b092b87fcd79223db199cd3d330f3d43689b47f345aa4e34028dcf1680d609a5d5a89ab08588e817b566d3b265834c38f1db580bc1c144b512ce74d35f2a174
 
 [build]
+if [ -n "$CROSS_COMPILE" ] ; then
+  xconfflags="--host=$($CC -dumpmachine|sed 's/musl/gnu/') \
+  --with-sysroot=$butch_root_dir --with-protoc=protoc"
+  type protoc >/dev/null || { 
+    echo "error: need protoc installed on the host" ; exit 1 ;
+  }
+fi
 CXXFLAGS="-D_GNU_SOURCE $optcflags" \
 CFLAGS="-D_GNU_SOURCE -DSTDC_HEADERS $optcflags" \
 LDFLAGS="$optldflags" \
- ./configure -C --prefix="$butch_prefix"
+ ./configure -C --prefix="$butch_prefix" $xconfflags
 make -j$MAKE_THREADS
 make DESTDIR="$butch_install_dir" install
